"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Download, FileText, RefreshCcw, CheckCircle2, AlertCircle } from "lucide-react";
import { DashboardHeader } from "../../components/dashboard/header";
import StarfieldBackground from "../../components/dashboard/swarm-background";

export default function DownloadsPage() {
  const [isDownloading, setIsDownloading] = useState(false);
  const [downloadStatus, setDownloadStatus] = useState<"idle" | "success" | "error">("idle");

  const handleDownloadReport = async () => {
    setIsDownloading(true);
    setDownloadStatus("idle");

    try {
      const res = await fetch("/api/report");

      if (!res.ok) throw new Error("Download failed");

      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;

      // Try to get filename from Content-Disposition header
      const disposition = res.headers.get("Content-Disposition");
      const filenameMatch = disposition?.match(/filename=(.+)/);
      a.download = filenameMatch ? filenameMatch[1].replace(/"/g, "") : "event_budget_report.pdf";

      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);

      setDownloadStatus("success");
    } catch (err) {
      console.error("Download error:", err);
      setDownloadStatus("error");
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div className="h-screen flex flex-col bg-[#080d12] text-white overflow-hidden">
      <StarfieldBackground />

      <div className="relative z-20">
        <DashboardHeader />
      </div>

      <div className="flex-1 overflow-y-auto relative z-10 px-8 py-12">
        <div className="max-w-2xl mx-auto space-y-8">
          {/* Page Title */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <h1 className="text-3xl font-bold text-white mb-2" style={{ fontFamily: "var(--font-orbitron, 'Orbitron', sans-serif)" }}>
              Downloads
            </h1>
            <p className="text-gray-400 text-sm">Download reports and assets generated by your swarm.</p>
          </motion.div>

          {/* Budget Report Card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="bg-[#0a1017] border border-[#1e293b] rounded-2xl p-6 space-y-5 shadow-[0_0_40px_rgba(0,229,255,0.05)]"
          >
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-xl bg-[#00e5ff]/10 border border-[#00e5ff]/20 flex items-center justify-center">
                <FileText className="w-6 h-6 text-[#00e5ff]" />
              </div>
              <div>
                <h3 className="text-white font-semibold text-lg">Event Budget Report</h3>
                <p className="text-gray-500 text-xs">Auto-generated financial summary for your event</p>
              </div>
            </div>

            <p className="text-gray-400 text-sm leading-relaxed">
              This report is dynamically generated by the AI swarm based on your event configuration, including estimated costs, resource allocation, and venue logistics.
            </p>

            <button
              onClick={handleDownloadReport}
              disabled={isDownloading}
              className={`w-full h-12 rounded-xl font-bold uppercase tracking-wider text-sm flex items-center justify-center gap-2 transition-all ${
                isDownloading
                  ? "bg-[#1e293b] text-gray-400 cursor-wait"
                  : downloadStatus === "success"
                  ? "bg-green-500/20 text-green-400 border border-green-500/30"
                  : downloadStatus === "error"
                  ? "bg-red-500/20 text-red-400 border border-red-500/30"
                  : "bg-[#00e5ff] hover:bg-[#00e5ff]/80 text-black"
              }`}
            >
              {isDownloading ? (
                <><RefreshCcw className="w-4 h-4 animate-spin" /> Generating Report...</>
              ) : downloadStatus === "success" ? (
                <><CheckCircle2 className="w-4 h-4" /> Downloaded!</>
              ) : downloadStatus === "error" ? (
                <><AlertCircle className="w-4 h-4" /> Download Failed — Try Again</>
              ) : (
                <><Download className="w-4 h-4" /> Download Budget Report</>
              )}
            </button>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
